locales:
  olo:
    name: Livvi Karelian Keyboards
    description: >-
      Mobile OS keyboards for the Livvi Karelian language from the Divvun group
      at UiT.
  en:
    name: Livvi Karelian Keyboards
    description: >-
      Mobile OS keyboards for the Livvi Karelian language from the Divvun group
      at UiT.
  nb:
    name: Livvi Karelian tastatur
    description: Mobiltastatur for Livvi Karelian fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
